---
- name: Create instances
  os_server:
    cloud:              "{{ openstack_cloud }}"
    state:              "{{ openstack_server_state | default('present') }}" 
    name:               "{{ __inst.instance_name }}"
    image:              "{{ __inst.image }}"
    key_name:           "{{ provisioning_ssh_key }}"
    flavor:             "{{ __inst.flavor | default('m2.medium') }}"
    security_groups:    "{{ __inst.security_group_name }}"
    delete_fip: yes
    wait: no
    nics:
      - net-name: int_network
    meta:               "group={{ __inst.group }},deployment_name={{ __inst.deployment }}"
    userdata: |
      #!/bin/bash
      curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
      cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
  loop: "{{ openstack_servers }}"
  loop_control:
    loop_var: __inst
  async: 900
  poll: 0
  register: r_instances

- name: Wait for async OSP instance creation to complete
  async_status: "jid={{ item.ansible_job_id }}"
  register: r_wait
  until: r_wait.finished
  retries: 900
  loop: "{{ r_instances.results }}"

- name: Debug instances 
  debug:
    msg: "Server is {{ __instance.__inst.instance_name }}"
    verbosity: 2
  loop: "{{ r_instances.results }}"
  loop_control:
    loop_var: __instance

- when: openstack_server_state != 'absent' | default(true)
  block:

    - name: Add floating IP to instances
      os_floating_ip:
        cloud: openstack
        state: "{{ openstack_server_state | default('present') }}"
        reuse: yes
        server: "{{ __instance.__inst.instance_name }}"
        network: ext_network
        wait: true
        timeout: 240 
      loop: "{{ r_instances.results }}"
      loop_control:
        loop_var: __instance
      register: r_floating_ips

    - name: Wait for servers by name to be available
      wait_for:
        host: "{{ __fip.floating_ip.floating_ip_address }}"
        port: 22
        search_regex: OpenSSH
        timeout: 720 
      loop: "{{ r_floating_ips.results }}"
      loop_control:
        loop_var: __fip
      delegate_to: "{{ inventory_hostname }}"

...
